blank_issues_enabled: false
contact_links:
  - name: Retail?
    url: https://github.com/DeadlyBossMods/DeadlyBossMods/issues/new/choose
    about: Is your issue for retail WoW?
  - name: Burning Crusade Classic?
    url: https://github.com/DeadlyBossMods/DBM-BCC/issues/new/choose
    about: Is your issue for Burning Crusade Classic WoW?
